/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package l2m.decoder.inmarsat;

public interface inmarsatAmbeConstants {
  public final static int AmbeAero_Frame_Len_Bytes = inmarsatAmbeJNI.AmbeAero_Frame_Len_Bytes_get();
}
