/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package l2m.decoder.inmarsat;

public class inmarsatAmbeJNI {

    static {
         boolean embeddedLibrary = EmbeddedLibraryTools.LOADED_EMBEDDED_LIBRARY;
    }

  public final static native int AmbeAero_Frame_Len_Bytes_get();
  public final static native long new_Inmarsat();
  public final static native void delete_Inmarsat(long jarg1);
  public final static native void Inmarsat_decode(long jarg1, Inmarsat jarg1_, byte[] jarg2, int jarg3, byte[] jarg4);
}
