/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package l2m.decoder.inmarsat;

public class Inmarsat {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Inmarsat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Inmarsat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        inmarsatAmbeJNI.delete_Inmarsat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Inmarsat() {
    this(inmarsatAmbeJNI.new_Inmarsat(), true);
  }

  public void decode(byte[] datas, int size, byte[] result) {
    inmarsatAmbeJNI.Inmarsat_decode(swigCPtr, this, datas, size, result);
  }

}
